### ISSUE TITLE
API=closed, network=open

### ISSUE THREAD

**Issue by martinthomson** [capport-wg/architecture#24]
David Bird points out:

> The section titled  "Risk of Nuisance Captive Portal" should really be
> talking about networks that USE the API and have NO network integration
> (e.g. Captive by API only, not by any network enforcement function).

This is a case we might address.

We might reason about this by comparison with imperfect blocking.  Say that a network failed to block your VPN provider, you might see no problem with existing probes if you only used the VPN.  Though many network stacks seem to like to probe before allowing any traffic, this might still happen.

**Comment by klarose** [comment]
So, not we're talking about the risk of a nuisance API. I think we had been calling this a non-issue because UE discovers the API from somewhat trusted sources -- DHCP/RA,PvD. 

But, let's assume that the API is a bad actor for some reason -- discovery was compromised, the API itself was compromised, or it's just plain broken.

Thinking about that case, you could have:
1. The API says that you have access when you don't.
2. The API says that you have access when you do.
3. The API says that you don't have access when you do.
4. The API says that you don't have access when you don't.

We don't need to worry about 2. and 4.

In case 1. the system will try to access the network and fail. Barring probe functionality, this means that the system will simply fail to attach to the network properly. There's no good solution without user intervention. With probes, I think it works out naturally -- the system will work as it does today.

In case 3. the UE will attempt to visit the portal. I can think of a few sub-cases here:
a) The URI of the portal is bad/non-existent
b) The URI is present, works and the portal says you have access
c) The URI is present, works and the portal refuses to grant access.

b) is easy: the UE proceeds with its connection and everything works.

We need to consider a) a bit, since it's a fairly likely failure mode. I think it's probably safe to assume that, barring probes, network access is unavailable on this network, and the system should treat it as such.
c) I think this should probably behave the same as a), though it's a bit nicer in that the user has actual feedback.

It's a little unfortunate that in the two cases I mentioned above, a) and c), the UE *should* have network access, but it does not give access to the user. So, perhaps the recommendation should be to treat it as though network access is unavailable, barring explicit confirmation from the user to use the network, or confirmation that network access is available through probes.

**Comment by klarose** [comment]
I'll post the above to the mailing list for general comments.

**Comment by martinthomson** [comment]
Discussed in Montreal:

This is not an issue that we need to address.  However, we do need to remove the word nuisance from the title.

**Comment by klarose** [comment]
Fixed in #32
