### ISSUE TITLE
What is the intent of the context-free URL section?

### ISSUE THREAD

**Issue by dcdolson** [capport-wg/architecture#63]
A reviewer writes,
```
> — Section 3.4.3 —
> Is this section talking about using a context-free URI as a UE
> identifier?  It should be clearer about that, if so (and if that’s not
> what it’s about, the section is misplaced).  There’s nothing in here
> that discusses how such identifiers would meet the specified criteria.
```

I think this is trying to say the server should not be looking at
Ethernet addresses, for example, because the server is probably not
on the same subnet as the User Equipment. So the info needs to be
in the URL.

Figure out what we're trying to say, and whether this is the right section for it.

**Comment by klarose** [comment]
That's exactly what it's talking about.

That said, while it is related to identifying the UE, it's not an example identifier.

It has been a while since I thought about this, and I wasn't at the meeting where it was discussed, but I think the intention here was to limit any URIs provide in the API to these context-free URIs. That is, the resource pointed to by the URI cannot depend on information not present in the URI.  For example, the API draft (https://tools.ietf.org/html/draft-ietf-capport-api-07#section-5) provides a 'user-portal-url'.

Suppose that URL is "captive-portal.example.com/login". That resource could be implemented by checking the source ethernet address of the connection to see if you're already logged in. But, that won't be correct if you're not in the same subnet.

Instead, the URL should be something like: "captive-portal.example.com/login?id=<user-equipment-id>"


So, this is more of a constraint on the API and how it uses identifiers than an example of an identifier. Did we just get the indentation wrong? Or was this a misunderstanding of what the working group requested?

**Comment by martinthomson** [comment]
Maybe all this needs is a preface explaining how some systems operate.

> A captive portal API needs to present information to clients that is unique to that client.  To do this, some systems use information from the context of a request, such as the source address, to identify the UE.
>
> Using information from context rather than information from the URI allows the same URI to be used for different clients.  However, it also means that the resource is unable to provide relevant information if the UE makes a request using a different network path.  This might happen when UE has multiple network interfaces.  It might also happen if the address of the API provided by DNS depends on where the query originates (as split DNS {{?RFC8499}}).
>
> Accessing the API MAY depend on contextual information.  However, the URLs provided in the API SHOULD be unique to the UE and not dependent on contextual information to function correctly.
>
> Though a URL might still correctly resolve when the UE makes the request from a different network, it is possible that some functions could be limited to when the UE makes requests using the captive network. For example, payment options could be absent or a warning could be displayed to indicate the payment is not for the current connection.
>
> URLs could include some means of identifying the User Equipment in the URLs.  However, including unauthenticated User Equipment identifiers in the URL may expose the service to spoofing or replay attacks.

The last two paragraphs are a direct copy of existing text.
